location = ["New York City", "Los Angeles", "Melbourne", "Tokyo", "Medan"]
print("This is the original list: {}".format(location))
print("This is the sorted list without modifying the stored list: {}".format(sorted(location)))
print("This is the proof that the list is still unmodified: {}".format(location))
print("This is the sorted list in backwards without modifying the stored list: {}".format(sorted(location, reverse=True)))
print("It is still unmodified: {}".format(location))
location.reverse()
print("The list has been reversed but untidy: {}".format(location))
location.reverse()
print("The list has been reversed to original again: {}".format(location))
location.sort()
print("The stored list has been sorted: {}".format(location))
location.sort(reverse=True)
print("This stored list is sorted in reverse order: {}".format(location))
